"""Survey metadata, extracted verbatim from ``WVS.py``.

Generated once with ``ast.literal_eval`` so the country/question tables
cannot drift from the analysis notebook by transcription error.
The only edits are the two spelling fixes noted in ``FAMILY_LABEL``.
"""

COUNTRY_INFO = {'AND': ['1',
         'Andorra',
         'AND',
         'Latin',
         '1004',
         '01-06-2018-22-09-2018',
         'PAPI',
         'Catalan,English,Spanish,French'],
 'ARG': ['2', 'Argentina', 'ARG', 'Latin', '1003', '04-07-2017-19-07-2017', 'PAPI', 'Spanish'],
 'ARM': ['4', 'Armenia', 'ARM', 'Other', '1223', '07-05-2021-07-06-2021', 'CAPI', 'Armenian'],
 'AUS': ['3',
         'Australia',
         'AUS',
         'Anglosphere',
         '1813',
         '06-04-2018-06-08-2018',
         'Mail/Post',
         'English'],
 'BGD': ['5',
         'Bangladesh',
         'BGD',
         'Indo-Iranian',
         '1200',
         '03-12-2018-24-12-2018',
         'PAPI',
         'Bengali'],
 'BOL': ['6', 'Bolivia', 'BOL', 'Latin', '2067', '18-01-2017-07-03-2017', 'CAPI', 'Spanish'],
 'BRA': ['7', 'Brazil', 'BRA', 'Latin', '1762', '15-05-2018-11-06-2018', 'CAPI', 'Portuguese'],
 'CAN': ['8',
         'Canada',
         'CAN',
         'Anglosphere',
         '4018',
         '02-10-2020-19-10-2020',
         'CAWI',
         'English,French'],
 'CDE': ['65',
         'Canada (English-speaking)',
         'CDE',
         'Anglosphere',
         '0',
         '11-02-2020-23-03-2020',
         'CAPI',
         'English'],
 'CDF': ['66',
         'Canada (French-speaking)',
         'CDF',
         'Latin',
         '0',
         '11-02-2020-23-03-2020',
         'CAPI',
         'French'],
 'CHL': ['9', 'Chile', 'CHL', 'Latin', '1000', '06-01-2018-05-02-2018', 'CAPI', 'Spanish'],
 'CHN': ['10', 'China', 'CHN', 'EastAsia', '3036', '07-07-2018-12-10-2018', 'PAPI', 'Chinese'],
 'COL': ['11', 'Colombia', 'COL', 'Latin', '1520', '30-11-2018-22-12-2018', 'CAPI', 'Spanish'],
 'CYP': ['12', 'Cyprus', 'CYP', 'Other', '1000', '13-05-2019-04-06-2019', 'PAPI', 'Greek,Turkish'],
 'CZE': ['13', 'Czechia', 'CZE', 'Slavic', '1200', '11-02-2022-13-05-2022', 'CAPI', 'Czech'],
 'DEU': ['17', 'Germany', 'DEU', 'Germanic', '1528', '25-10-2017-31-03-2018', 'CAPI', 'German'],
 'ECU': ['14', 'Ecuador', 'ECU', 'Latin', '1200', '24-01-2018-03-03-2018', 'CAPI', 'Spanish'],
 'EGY': ['15', 'Egypt', 'EGY', 'Semetic', '1200', '22-06-2018-07-07-2018', 'CAPI', 'Arabic'],
 'ETH': ['16',
         'Ethiopia',
         'ETH',
         'Semetic',
         '1230',
         '06-02-2020-19-03-2020',
         'CAPI',
         'Amharic,Oromo,Tigris'],
 'GBR': ['19',
         'Great_Britain',
         'GBR',
         'Anglosphere',
         '2609',
         '02-03-2022-07-09-2022',
         'CAPI/CAWI/Post/Video_interviewing',
         'English'],
 'GRC': ['18', 'Greece', 'GRC', 'Other', '1200', '08-09-2017-16-10-2017', 'PAPI', 'Greek'],
 'GTM': ['20', 'Guatemala', 'GTM', 'Latin', '1203', '03-10-2019-25-02-2020', 'CAPI', 'Spanish'],
 'HKG': ['21',
         'Hong_Kong_SAR',
         'HKG',
         'EastAsia',
         '2075',
         '16-07-2018-11-11-2018',
         'PAPI/CAWI',
         'Cantonese,English,Putonghua'],
 'IND': ['67',
         'India',
         'IND',
         'Indo-Iranian',
         '4090',
         '01-01-2023-31-03-2023',
         'CAPI',
         'Hindi,English'],
 'IDN': ['22',
         'Indonesia',
         'IDN',
         'EastAsia',
         '3200',
         '01-06-2018-20-08-2018',
         'CAPI',
         'Indonesian'],
 'IRN': ['23', 'Iran', 'IRN', 'Indo-Iranian', '1499', '24-03-2020-17-04-2020', 'PAPI', 'Persian'],
 'IRQ': ['24', 'Iraq', 'IRQ', 'Semetic', '1200', '08-06-2018-28-06-2018', 'CAPI/PAPI', 'Arabic'],
 'JOR': ['26', 'Jordan', 'JOR', 'Semetic', '1203', '07-06-2018-14-06-2018', 'CAPI', 'Arabic'],
 'JPN': ['25',
         'Japan',
         'JPN',
         'EastAsia',
         '1353',
         '05-09-2019-26-09-2019',
         'Mail/Post',
         'Japanese'],
 'KAZ': ['27',
         'Kazakhstan',
         'KAZ',
         'Turkic',
         '1276',
         '01-10-2018-30-11-2018',
         'PAPI',
         'Kazakh,Russian'],
 'KZK': ['27',
         'Kazakhstan (Kazakh-speaking)',
         'KZK',
         'Turkic',
         '1276',
         '01-10-2018-30-11-2018',
         'PAPI',
         'Kazakh,Russian'],
 'KZR': ['27',
         'Kazakhstan (Russian-speaking)',
         'KZR',
         'Slavic',
         '1276',
         '01-10-2018-30-11-2018',
         'PAPI',
         'Kazakh,Russian'],
 'KEN': ['28',
         'Kenya',
         'KEN',
         'SubSaharanAfrica',
         '1266',
         '22-05-2021-22-06-2022',
         'CAPI',
         'Swahili'],
 'KGZ': ['29',
         'Kyrgyzstan',
         'KGZ',
         'Turkic',
         '1200',
         '05-12-2019-28-01-2020',
         'CAPI',
         'Kirghiz,Russian'],
 'KOR': ['53', 'South_Korea', 'KOR', 'EastAsia', '1245', '24-12-2017-16-01-2018', 'CAPI', 'Korean'],
 'LBN': ['30', 'Lebanon', 'LBN', 'Semetic', '1200', '04-06-2018-18-06-2018', 'CAPI', 'Arabic'],
 'LBY': ['31', 'Libya', 'LBY', 'Semetic', '1196', '12-12-2021-26-01-2022', 'CAPI', 'Arabic'],
 'MAC': ['32', 'Macau_SAR', 'MAC', 'EastAsia', '1023', '03-10-2019-17-12-2019', 'CAPI', 'Chinese'],
 'MAR': ['37', 'Morocco', 'MAR', 'Semetic', '1200', '01-11-2021-19-12-2021', 'PAPI', 'Arabic'],
 'MDV': ['34',
         'Maldives',
         'MDV',
         'Indo-Iranian',
         '1038',
         '01-09-2021-01-10-2021',
         'CAPI',
         'Dhivehi'],
 'MEX': ['35', 'Mexico', 'MEX', 'Latin', '1739', '18-01-2018-02-05-2018', 'PAPI', 'Spanish'],
 'MMR': ['38', 'Myanmar', 'MMR', 'EastAsia', '1200', '17-01-2020-03-03-2020', 'CAPI', 'Burmese'],
 'MNG': ['36', 'Mongolia', 'MNG', 'Turkic', '1638', '04-09-2019-06-02-2021', 'CAPI', 'Mongolian'],
 'MYS': ['33',
         'Malaysia',
         'MYS',
         'EastAsia',
         '1313',
         '05-04-2018-21-05-2018',
         'CAWI/CAPI',
         'Malay,Chinese'],
 'NGA': ['42',
         'Nigeria',
         'NGA',
         'SubSaharanAfrica',
         '1237',
         '19-12-2017-26-01-2018',
         'CAPI',
         'Hausa,Igbo,Yoruba,English'],
 'NIC': ['41', 'Nicaragua', 'NIC', 'Latin', '1200', '30-11-2019-05-01-2020', 'CAPI', 'Spanish'],
 'NIR': ['43',
         'Northern_Ireland',
         'NIR',
         'Anglosphere',
         '447',
         '01-03-2022-07-09-2022',
         'CAPI/CAWI/Post/Video_interviewing',
         'English'],
 'NLD': ['39', 'Netherlands', 'NLD', 'Germanic', '2145', '03-01-2022-25-01-2022', 'CAWI', 'Dutch'],
 'NZL': ['40',
         'New_Zealand',
         'NZL',
         'Anglosphere',
         '1057',
         '04-07-2019-21-02-2020',
         'Mail/Post',
         'English'],
 'PAK': ['44', 'Pakistan', 'PAK', 'Indo-Iranian', '1995', '04-11-2018-11-12-2018', 'CAPI', 'Urdu'],
 'PER': ['45', 'Peru', 'PER', 'Latin', '1400', '17-08-2018-09-09-2018', 'PAPI', 'Spanish'],
 'PHL': ['46',
         'Philippines',
         'PHL',
         'EastAsia',
         '1200',
         '03-12-2019-09-12-2019',
         'PAPI',
         'Bikol,Cebuano,Filipino,Ikolo,Tausug,Waray,Hiligaynon'],
 'PRI': ['47', 'Puerto_Rico', 'PRI', 'Latin', '1127', '16-03-2018-27-10-2018', 'PAPI', 'Spanish'],
 'ROU': ['48', 'Romania', 'ROU', 'Latin', '1257', '30-11-2017-02-04-2018', 'CAPI', 'Romanian'],
 'RUS': ['49', 'Russia', 'RUS', 'Slavic', '1810', '07-11-2017-29-12-2017', 'CAPI/PAPI', 'Russian'],
 'SGP': ['51',
         'Singapore',
         'SGP',
         'EastAsia',
         '2012',
         '08-11-2019-15-03-2020',
         'PAPI',
         'English,Malay,Chinese'],
 'SRB': ['50', 'Serbia', 'SRB', 'Slavic', '1046', '20-05-2017-07-07-2017', 'PAPI', 'Serbian'],
 'SVK': ['52', 'Slovakia', 'SVK', 'Slavic', '1200', '19-01-2022-22-02-2022', 'CAPI', 'Slovak'],
 'THA': ['56', 'Thailand', 'THA', 'EastAsia', '1500', '01-12-2017-26-02-2018', 'PAPI', 'Thai'],
 'TJK': ['55',
         'Tajikistan',
         'TJK',
         'Indo-Iranian',
         '1200',
         '08-01-2020-06-02-2020',
         'CAPI',
         'Tajik,Russian'],
 'TUN': ['57', 'Tunisia', 'TUN', 'Semetic', '1208', '26-04-2019-20-05-2019', 'CAPI', 'Arabic'],
 'TUR': ['58', 'Turkey', 'TUR', 'Turkic', '2415', '31-03-2018-21-05-2018', 'PAPI', 'Turkish'],
 'TWN': ['54', 'Taiwan_ROC', 'TWN', 'EastAsia', '1223', '25-03-2019-16-06-2019', 'CAPI', 'Chinese'],
 'UKR': ['59',
         'Ukraine',
         'UKR',
         'Slavic',
         '1289',
         '25-07-2020-14-08-2020',
         'CAPI',
         'Ukrainian,Russian'],
 'URY': ['61', 'Uruguay', 'URY', 'Latin', '1000', '27-01-2022-22-03-2022', 'CAPI', 'Spanish'],
 'USA': ['60',
         'United_States',
         'USA',
         'Anglosphere',
         '2596',
         '28-04-2017-31-05-2017',
         'CAWI/CATI',
         'English'],
 'USS': ['60',
         'United_States_South',
         'USS',
         'Anglosphere',
         '2596',
         '28-04-2017-31-05-2017',
         'CAWI/CATI',
         'English'],
 'USN': ['60',
         'United_States_North',
         'USN',
         'Anglosphere',
         '2596',
         '28-04-2017-31-05-2017',
         'CAWI/CATI',
         'English'],
 'USD': ['67',
         'United_States_Democrats',
         'USD',
         'Anglosphere',
         '2596',
         '28-04-2017-31-05-2017',
         'CAWI/CATI',
         'English'],
 'USR': ['68',
         'United_States_Republicans',
         'USR',
         'Anglosphere',
         '2596',
         '28-04-2017-31-05-2017',
         'CAWI/CATI',
         'English'],
 'UZB': ['68',
         'Uzbekistan',
         'UZB',
         'Turkic',
         '1200',
         '01-06-2022-30-08-2022',
         'CAPI',
         'Uzbek,Russian'],
 'VEN': ['62', 'Venezuela', 'VEN', 'Latin', '1190', '03-05-2021-26-07-2021', 'PAPI', 'Spanish'],
 'VNM': ['63', 'Vietnam', 'VNM', 'EastAsia', '1200', '15-12-2019-21-01-2020', 'CAPI', 'Vietnamese'],
 'ZWE': ['64',
         'Zimbabwe',
         'ZWE',
         'SubSaharanAfrica',
         '1215',
         '11-02-2020-23-03-2020',
         'CAPI',
         'English,Shona,Ndebele'],
 'CANCHN': ['65',
            'Canadian Chinese',
            'CAN',
            'EastAsia',
            '0',
            '11-02-2020-23-03-2020',
            'CAPI',
            'English'],
 'USASPN': ['66',
            'American Spanish',
            'USA',
            'Latin',
            '0',
            '11-02-2020-23-03-2020',
            'CAPI',
            'English'],
 'GRBPLS': ['67',
            'Great Britain Polish',
            'GBR',
            'Slavic',
            '0',
            '11-02-2020-23-03-2020',
            'CAPI',
            'English'],
 'AUSCHN': ['68',
            'Australian Chinese',
            'AUS',
            'EastAsia',
            '0',
            '11-02-2020-23-03-2020',
            'CAPI',
            'English'],
 'NZLCHN': ['69',
            'New Zealand Chinese',
            'NZL',
            'EastAsia',
            '0',
            '11-02-2020-23-03-2020',
            'CAPI',
            'English'],
 'DEUTRK': ['70',
            'German Turkish',
            'DEU',
            'Turkic',
            '0',
            '11-02-2020-23-03-2020',
            'CAPI',
            'English'],
 'NLDENG': ['71',
            'Netherlands English',
            'NLD',
            'Anglosphere',
            '0',
            '11-02-2020-23-03-2020',
            'CAPI',
            'English']}

LANGUAGE_FAMILY = {'AND': 'Latin',
 'ARG': 'Latin',
 'AUS': 'Anglosphere',
 'BGD': 'Indo-Iranian',
 'ARM': 'Other',
 'BOL': 'Latin',
 'BRA': 'Latin',
 'MMR': 'EastAsia',
 'CAN': 'Anglosphere',
 'CHL': 'Latin',
 'CHN': 'EastAsia',
 'TWN': 'EastAsia',
 'COL': 'Latin',
 'CYP': 'Other',
 'CZE': 'Slavic',
 'ECU': 'Latin',
 'ETH': 'Semetic',
 'DEU': 'Germanic',
 'GRC': 'Other',
 'GTM': 'Latin',
 'HKG': 'EastAsia',
 'IDN': 'EastAsia',
 'IND': 'Indo-Iranian',
 'IRN': 'Indo-Iranian',
 'IRQ': 'Semetic',
 'JPN': 'EastAsia',
 'KAZ': 'Turkic',
 'JOR': 'Semetic',
 'KEN': 'SubSaharanAfrica',
 'KOR': 'EastAsia',
 'KGZ': 'Turkic',
 'LBN': 'Semetic',
 'LBY': 'Semetic',
 'MAC': 'EastAsia',
 'MYS': 'EastAsia',
 'MDV': 'Indo-Iranian',
 'MEX': 'Latin',
 'MNG': 'Turkic',
 'MAR': 'Semetic',
 'NLD': 'Germanic',
 'NZL': 'Anglosphere',
 'NIC': 'Latin',
 'NGA': 'SubSaharanAfrica',
 'PAK': 'Indo-Iranian',
 'PER': 'Latin',
 'PHL': 'EastAsia',
 'PRI': 'Latin',
 'ROU': 'Latin',
 'RUS': 'Slavic',
 'SRB': 'Slavic',
 'SGP': 'EastAsia',
 'SVK': 'Slavic',
 'VNM': 'EastAsia',
 'ZWE': 'SubSaharanAfrica',
 'TJK': 'Indo-Iranian',
 'THA': 'EastAsia',
 'TUN': 'Semetic',
 'TUR': 'Turkic',
 'UKR': 'Slavic',
 'EGY': 'Semetic',
 'GBR': 'Anglosphere',
 'USA': 'Anglosphere',
 'URY': 'Latin',
 'UZB': 'Slavic',
 'VEN': 'Latin',
 'NIR': 'Anglosphere',
 'CDE': 'Anglosphere',
 'CDF': 'Latin',
 'USN': 'Anglosphere',
 'USS': 'Anglosphere',
 'USD': 'Anglosphere',
 'USR': 'Anglosphere',
 'KZK': 'Turkic',
 'KZR': 'Slavic',
 'CANCHN': 'EastAsia',
 'USASPN': 'Latin',
 'GRBPLS': 'Slavic',
 'AUSCHN': 'EastAsia',
 'NZLCHN': 'EastAsia',
 'DEUTRK': 'Turkic',
 'NLDENG': 'Anglosphere'}

QUESTIONS = {'Q1': {'question': 'Important in life: Family', 'category': 'Morality'},
 'Q2': {'question': 'Important in life: Friends', 'category': 'Morality'},
 'Q3': {'question': 'Important in life: Leisure time', 'category': 'Economical'},
 'Q4': {'question': 'Important in life: Politics', 'category': 'Politics'},
 'Q5': {'question': 'Important in life: Work', 'category': 'Economical'},
 'Q6': {'question': 'Important in life: Religion', 'category': 'Religion'},
 'Q7': {'question': 'Important child qualities: good manners', 'category': 'Morality'},
 'Q8': {'question': 'Important child qualities: independence', 'category': 'Morality'},
 'Q9': {'question': 'Important child qualities: hard work', 'category': 'Morality'},
 'Q10': {'question': 'Important child qualities: feeling of responsibility',
         'category': 'Morality'},
 'Q11': {'question': 'Important child qualities: imagination', 'category': 'Morality'},
 'Q12': {'question': 'Important child qualities: tolerance and respect for other people',
         'category': 'Morality'},
 'Q13': {'question': 'Important child qualities: thrift saving money and things',
         'category': 'Economical'},
 'Q14': {'question': 'Important child qualities: determination perseverance',
         'category': 'Morality'},
 'Q15': {'question': 'Important child qualities: religious faith', 'category': 'Religion'},
 'Q16': {'question': 'Important child qualities: unselfishness', 'category': 'Morality'},
 'Q17': {'question': 'Important child qualities: obedience', 'category': 'Morality'},
 'Q18': {'question': 'Neighbors: Drug addicts', 'category': 'Morality'},
 'Q19': {'question': 'Neighbors: People of a different race', 'category': 'Morality'},
 'Q20': {'question': 'Neighbors: People who have AIDS', 'category': 'Morality'},
 'Q21': {'question': 'Neighbors: Immigrants/foreign workers', 'category': 'Morality'},
 'Q22': {'question': 'Neighbors: Homosexuals', 'category': 'Morality'},
 'Q23': {'question': 'Neighbors: People of a different religion', 'category': 'Religion'},
 'Q24': {'question': 'Neighbors: Heavy drinkers', 'category': 'Morality'},
 'Q25': {'question': 'Neighbors: Unmarried couples living together', 'category': 'Morality'},
 'Q26': {'question': 'Neighbors: People who speak a different language', 'category': 'Morality'},
 'Q27': {'question': 'One of main goals in life has been to make my parents proud',
         'category': 'Morality'},
 'Q28': {'question': 'Pre-school child suffers with working mother', 'category': 'Gender'},
 'Q29': {'question': 'Men make better political leaders than women do', 'category': 'Gender'},
 'Q30': {'question': 'University is more important for a boy than for a girl',
         'category': 'Gender'},
 'Q31': {'question': 'Men make better business executives than women do', 'category': 'Gender'},
 'Q32': {'question': 'Being a housewife just as fulfilling', 'category': 'Gender'},
 'Q33': {'question': 'Jobs scarce: Men should have more right to a job than women',
         'category': 'Gender'},
 'Q33_3': {'question': 'Jobs scarce: Men should have more right to a job than women (3-point '
                       'scale)',
           'category': 'Gender'},
 'Q34': {'question': 'Jobs scarce: Employers should give priority to (nation) people than '
                     'immigrants',
         'category': 'Politics'},
 'Q34_3': {'question': 'Jobs scarce: Employers should give priority to (nation) people than '
                       'immigrants (3-point scale)',
           'category': 'Politics'},
 'Q35': {'question': 'Problem if women have more income than husband', 'category': 'Gender'},
 'Q35_3': {'question': 'Problem if women have more income than husband (3-point scale)',
           'category': 'Gender'},
 'Q36': {'question': 'Homosexual couples are as good parents as other couples',
         'category': 'Morality'},
 'Q37': {'question': 'Duty towards society to have children', 'category': 'Morality'},
 'Q38': {'question': 'It is children duty to take care of ill parent', 'category': 'Morality'},
 'Q39': {'question': 'People who do not work turn lazy', 'category': 'Economical'},
 'Q40': {'question': 'Work is a duty towards society', 'category': 'Economical'},
 'Q41': {'question': 'Work should always come first even if it means less spare time',
         'category': 'Economical'},
 'Q42': {'question': 'Basic kinds of attitudes concerning society', 'category': 'Politics'},
 'Q43': {'question': 'Future changes: Less importance placed on work', 'category': 'Economical'},
 'Q44': {'question': 'Future changes: More emphasis on technology', 'category': 'Economical'},
 'Q45': {'question': 'Future changes: Greater respect for authority', 'category': 'Politics'},
 'Q46': {'question': 'Feeling of happiness', 'category': 'Morality'},
 'Q47': {'question': 'State of health (subjective)', 'category': 'Morality'},
 'Q48': {'question': 'How much freedom of choice and control', 'category': 'Morality'},
 'Q49': {'question': 'Satisfaction with your life', 'category': 'Morality'},
 'Q50': {'question': 'Satisfaction with financial situation of household',
         'category': 'Economical'},
 'Q51': {'question': 'Frequency you/family (last 12 month): Gone without enough food to eat',
         'category': 'Economical'},
 'Q52': {'question': 'Frequency you/family (last 12 month): Felt unsafe from crime in your own '
                     'home',
         'category': 'Morality'},
 'Q53': {'question': 'Frequency you/family (last 12 month): Gone without needed medicine or '
                     'treatment that you needed',
         'category': 'Economical'},
 'Q54': {'question': 'Frequency you/family (last 12 month): Gone without a cash income',
         'category': 'Economical'},
 'Q55': {'question': 'In the last 12 month, how often have you or your family: Gone without a safe '
                     'shelter over your head',
         'category': 'Economical'},
 'Q56': {'question': 'Standard of living comparing with your parents', 'category': 'Economical'},
 'Q57': {'question': 'Most people can be trusted', 'category': 'Morality'},
 'Q58': {'question': 'Trust: Your family', 'category': 'Morality'},
 'Q59': {'question': 'Trust: Your neighborhood', 'category': 'Morality'},
 'Q60': {'question': 'Trust: People you know personally', 'category': 'Morality'},
 'Q61': {'question': 'Trust: People you meet for the first time', 'category': 'Morality'},
 'Q62': {'question': 'Trust: People of another religion', 'category': 'Morality'},
 'Q63': {'question': 'Trust: People of another nationality', 'category': 'Morality'},
 'Q64': {'question': 'Confidence: Churches', 'category': 'Religion'},
 'Q65': {'question': 'Confidence: Armed Forces', 'category': 'Politics'},
 'Q66': {'question': 'Confidence: The Press', 'category': 'Politics'},
 'Q67': {'question': 'Confidence: Television', 'category': 'Politics'},
 'Q68': {'question': 'Confidence: Labor Unions', 'category': 'Politics'},
 'Q69': {'question': 'Confidence: The Police', 'category': 'Politics'},
 'Q70': {'question': 'Confidence: Justice System/Courts', 'category': 'Politics'},
 'Q71': {'question': 'Confidence: The Government', 'category': 'Politics'},
 'Q72': {'question': 'Confidence: The Political Parties', 'category': 'Politics'},
 'Q73': {'question': 'Confidence: Parliament', 'category': 'Politics'},
 'Q74': {'question': 'Confidence: The Civil Services', 'category': 'Politics'},
 'Q75': {'question': 'Confidence: Universities', 'category': 'Morality'},
 'Q76': {'question': 'Confidence: Elections', 'category': 'Politics'},
 'Q77': {'question': 'Confidence: Major Companies', 'category': 'Economical'},
 'Q78': {'question': 'Confidence: Banks', 'category': 'Economical'},
 'Q79': {'question': 'Confidence: The Environmental Protection Movement', 'category': 'Morality'},
 'Q80': {'question': "Confidence: The Women's Movement", 'category': 'Gender'},
 'Q81': {'question': 'Confidence: Charitable or humanitarian organizations',
         'category': 'Morality'},
 'Q82': {'question': 'Confidence: Major regional organization (combined from country-specific)',
         'category': 'Politics'},
 'Q82_NAFTA': {'question': 'Confidence: The North American Free Trade Agreement (NAFTA)',
               'category': 'Politics'},
 'Q83': {'question': 'Confidence: The United Nations (UN)', 'category': 'Politics'},
 'Q84': {'question': 'Confidence: International Monetary Fund (IMF)', 'category': 'Religion'},
 'Q85': {'question': 'Confidence: International Criminal Court (ICC)', 'category': 'Politics'},
 'Q86': {'question': 'Confidence: North Atlantic Treaty Organization (NATO)',
         'category': 'Politics'},
 'Q87': {'question': 'Confidence: The World Bank (WB)', 'category': 'Economical'},
 'Q88': {'question': 'Confidence: The World Health Organization (WHO)', 'category': 'Morality'},
 'Q89': {'question': 'Confidence: The World Trade Organization (WTO)', 'category': 'Economical'},
 'Q90': {'question': 'International organizations: being effective vs being democratic',
         'category': 'Politics'},
 'Q91': {'question': 'Countries with the permanent seats on the UN Security Council',
         'category': 'Politics'},
 'Q92': {'question': 'Where are the headquarters of the International Monetary Fund (IMF) located?',
         'category': 'Economical'},
 'Q93': {'question': 'Which of the following problems does the organization Amnesty International '
                     'deal with?',
         'category': 'Morality'},
 'Q94': {'question': 'Active/Inactive membership: church or religious org', 'category': 'Religion'},
 'Q94R': {'question': 'Active/Inactive membership: church or religious org',
          'category': 'Religion'},
 'Q95': {'question': 'Active/Inactive membership: sport or recreational org',
         'category': 'Economical'},
 'Q95R': {'question': 'Active/Inactive membership: sport or recreational org',
          'category': 'Economical'},
 'Q96': {'question': 'Active/Inactive membership: art, music, educational org',
         'category': 'Morality'},
 'Q96R': {'question': 'Active/Inactive membership: art, music, educational org',
          'category': 'Morality'},
 'Q97': {'question': 'Active/Inactive membership: labor union', 'category': 'Morality'},
 'Q97R': {'question': 'Active/Inactive membership: labor union', 'category': 'Morality'},
 'Q98': {'question': 'Active/Inactive membership: political party', 'category': 'Politics'},
 'Q98R': {'question': 'Active/Inactive membership: political party', 'category': 'Politics'},
 'Q99': {'question': 'Active/Inactive membership: environmental organization',
         'category': 'Morality'},
 'Q99R': {'question': 'Active/Inactive membership: environmental organization',
          'category': 'Morality'},
 'Q100': {'question': 'Active/Inactive membership: professional organization',
          'category': 'Economical'},
 'Q100R': {'question': 'Active/Inactive membership: professional organization',
           'category': 'Economical'},
 'Q101': {'question': 'Active/Inactive membership: charitable/humanitarian organization',
          'category': 'Morality'},
 'Q101R': {'question': 'Active/Inactive membership: charitable/humanitarian organization',
           'category': 'Morality'},
 'Q102': {'question': 'Active/Inactive membership: consumer organization', 'category': 'Morality'},
 'Q102R': {'question': 'Active/Inactive membership: consumer organization', 'category': 'Morality'},
 'Q103': {'question': 'Active/Inactive membership: self-help group, mutual aid group',
          'category': 'Morality'},
 'Q103R': {'question': 'Active/Inactive membership: self-help group, mutual aid group',
           'category': 'Morality'},
 'Q104': {'question': "Active/Inactive membership: women's group", 'category': 'Gender'},
 'Q104R': {'question': "Active/Inactive membership: women's group", 'category': 'Gender'},
 'Q105': {'question': 'Active/Inactive membership: other organization', 'category': 'Morality'},
 'Q105R': {'question': 'Active/Inactive membership: other organization', 'category': 'Morality'},
 'Q106': {'question': 'Income equality vs larger income differences', 'category': 'Economical'},
 'Q107': {'question': 'Private vs state ownership of business', 'category': 'Economical'},
 'Q108': {'question': "Government's vs individual's responsibility", 'category': 'Politics'},
 'Q109': {'question': 'Competition good or harmful', 'category': 'Economical'},
 'Q110': {'question': 'Success: hard work vs luck', 'category': 'Morality'},
 'Q111': {'question': 'Protecting environment vs. Economic growth', 'category': 'Morality'},
 'Q112': {'question': 'Perceptions of corruption in the country', 'category': 'Politics'},
 'Q113': {'question': 'Involved in corruption: State authorities', 'category': 'Politics'},
 'Q114': {'question': 'Involved in corruption: Business executives', 'category': 'Politics'},
 'Q115': {'question': 'Involved in corruption: Local authorities', 'category': 'Politics'},
 'Q116': {'question': 'Involved in corruption: Civil service providers', 'category': 'Politics'},
 'Q117': {'question': 'Involved in corruption: Journalists and media', 'category': 'Politics'},
 'Q118': {'question': 'Frequency ordinary people pay a bribe, give a gift or do a favor to local '
                      'officials/service providers in order to get services',
          'category': 'Politics'},
 'Q119': {'question': 'Degree of agreement: On the whole, women are less corrupt than men',
          'category': 'Gender'},
 'Q120': {'question': 'Risk to be held accountable for giving or receiving a bribe',
          'category': 'Politics'},
 'Q121': {'question': 'Impact of immigrants on the development of the country',
          'category': 'Politics'},
 'Q122': {'question': 'Immigration in your country: Fills useful jobs in the workforce',
          'category': 'Politics'},
 'Q123': {'question': 'Immigration in your country: Strengthens cultural diversity',
          'category': 'Politics'},
 'Q124': {'question': 'Immigration in your country: Increases the crime rate',
          'category': 'Politics'},
 'Q125': {'question': 'Immigration in your country: Gives asylum to political refugees',
          'category': 'Politics'},
 'Q126': {'question': 'Immigration in your country: Increases the risks of terrorism',
          'category': 'Politics'},
 'Q127': {'question': 'Immigration in your country: Helps poor people establish new lives',
          'category': 'Politics'},
 'Q128': {'question': 'Immigration in your country: Increases unemployment',
          'category': 'Politics'},
 'Q129': {'question': 'Immigration in your country: Leads to social conflict',
          'category': 'Politics'},
 'Q130': {'question': 'Immigration policy preference', 'category': 'Politics'},
 'Q131': {'question': 'Secure in neighborhood', 'category': 'Security'},
 'Q132': {'question': 'Frequency in your neighborhood: Robberies', 'category': 'Security'},
 'Q133': {'question': 'Frequency in your neighborhood: Alcohol consumed in the streets',
          'category': 'Security'},
 'Q134': {'question': "Frequency in your neighborhood: Police or military interfere with people's "
                      'private life',
          'category': 'Security'},
 'Q135': {'question': 'Frequency in your neighborhood: Racist behavior', 'category': 'Security'},
 'Q136': {'question': 'Frequency in your neighborhood: Drug sale in streets',
          'category': 'Security'},
 'Q137': {'question': 'Frequency in your neighborhood: Street violence and fights',
          'category': 'Security'},
 'Q138': {'question': 'Frequency in your neighborhood: Sexual harassment', 'category': 'Morality'},
 'Q139': {'question': "Things done for reasons of security: Didn't carry much money",
          'category': 'Security'},
 'Q140': {'question': 'Things done for reasons of security: Preferred not to go out at night',
          'category': 'Security'},
 'Q141': {'question': 'Things done for reasons of security: Carried a knife, gun or other weapon',
          'category': 'Security'},
 'Q142': {'question': 'Worries: Losing my job or not finding a job', 'category': 'Economical'},
 'Q143': {'question': "Worries: Not being able to give one's children a good education",
          'category': 'Economical'},
 'Q144': {'question': 'Respondent was victim of a crime during the past year',
          'category': 'Security'},
 'Q145': {'question': "Respondent's family was victim of a crime during last year",
          'category': 'Security'},
 'Q146': {'question': 'Worries: A war involving my country', 'category': 'Politics'},
 'Q147': {'question': 'Worries: A terrorist attack', 'category': 'Politics'},
 'Q148': {'question': 'Worries: A civil war', 'category': 'Politics'},
 'Q149': {'question': 'Freedom and Equality - Which more important', 'category': 'Morality'},
 'Q150': {'question': 'Freedom and security - Which more important', 'category': 'Morality'},
 'Q151': {'question': 'Willingness to fight for country', 'category': 'Politics'},
 'Q152': {'question': 'Aims of country: first choice', 'category': 'Politics'},
 'Q153': {'question': 'Aims of country: second choice', 'category': 'Politics'},
 'Q154': {'question': 'Aims of respondent: first choice', 'category': 'Politics'},
 'Q155': {'question': 'Aims of respondent: second choice', 'category': 'Politics'},
 'Q156': {'question': 'Most important: first choice', 'category': 'Morality'},
 'Q157': {'question': 'Most important: second choice', 'category': 'Morality'},
 'Q158': {'question': 'Science and technology are making our lives healthier, easier, and more '
                      'comfortable',
          'category': 'Economical'},
 'Q159': {'question': 'Because of science and technology, there will be more opportunities for the '
                      'next generation',
          'category': 'Economical'},
 'Q160': {'question': 'We depend too much on science and not enough on faith',
          'category': 'Religion'},
 'Q161': {'question': "One of the bad effects of science is that it breaks down people's ideas of "
                      'right and wrong',
          'category': 'Religion'},
 'Q162': {'question': 'It is not important for me to know about science in my daily life',
          'category': 'Economical'},
 'Q163': {'question': 'The world is better off, or worse off, because of science and technology',
          'category': 'Economical'},
 'Q164': {'question': 'Importance of God', 'category': 'Religion'},
 'Q165': {'question': 'Believe in: God', 'category': 'Religion'},
 'Q166': {'question': 'Believe in: life after death', 'category': 'Religion'},
 'Q167': {'question': 'Believe in: hell', 'category': 'Religion'},
 'Q168': {'question': 'Believe in: heaven', 'category': 'Religion'},
 'Q169': {'question': 'Whenever science and religion conflict, religion is always right',
          'category': 'Religion'},
 'Q170': {'question': 'The only acceptable religion is my religion', 'category': 'Religion'},
 'Q171': {'question': 'How often do you attend religious services', 'category': 'Religion'},
 'Q172': {'question': 'How often do you pray', 'category': 'Religion'},
 'Q172R': {'question': 'How often do you pray (Constructed)', 'category': 'Religion'},
 'Q173': {'question': 'Religious person', 'category': 'Religion'},
 'Q174': {'question': 'Meaning of religion: To follow religious norms and ceremonies vs To do good '
                      'to other people',
          'category': 'Religion'},
 'Q175': {'question': 'Meaning of religion: To make sense of life after death vs To make sense of '
                      'life in this world',
          'category': 'Religion'},
 'Q176': {'question': 'Degree of agreement: Nowadays one often has trouble deciding which moral '
                      'rules are the right ones to follow',
          'category': 'Morality'},
 'Q177': {'question': 'Justifiable: Claiming government benefits to which you are not entitled',
          'category': 'Morality'},
 'Q178': {'question': 'Justifiable: Avoiding a fare on public transport', 'category': 'Morality'},
 'Q179': {'question': 'Justifiable: Stealing property', 'category': 'Morality'},
 'Q180': {'question': 'Justifiable: Cheating on taxes', 'category': 'Morality'},
 'Q181': {'question': 'Justifiable: Someone accepting a bribe in the course of their duties',
          'category': 'Morality'},
 'Q182': {'question': 'Justifiable: Homosexuality', 'category': 'Morality'},
 'Q183': {'question': 'Justifiable: Prostitution', 'category': 'Morality'},
 'Q184': {'question': 'Justifiable: Abortion', 'category': 'Morality'},
 'Q185': {'question': 'Justifiable: Divorce', 'category': 'Morality'},
 'Q186': {'question': 'Justifiable: Sex before marriage', 'category': 'Morality'},
 'Q187': {'question': 'Justifiable: Suicide', 'category': 'Morality'},
 'Q188': {'question': 'Justifiable: Euthanasia', 'category': 'Morality'},
 'Q189': {'question': 'Justifiable: For a man to beat his wife', 'category': 'Morality'},
 'Q190': {'question': 'Justifiable: Parents beating children', 'category': 'Morality'},
 'Q191': {'question': 'Justifiable: Violence against other people', 'category': 'Morality'},
 'Q192': {'question': 'Justifiable: Terrorism as a political, ideological or religious mean',
          'category': 'Politics'},
 'Q193': {'question': 'Justifiable: Having casual sex', 'category': 'Morality'},
 'Q194': {'question': 'Justifiable: Political violence', 'category': 'Politics'},
 'Q195': {'question': 'Justifiable: Death penalty', 'category': 'Politics'},
 'Q196': {'question': 'Government has the right: Keep people under video surveillance in public '
                      'areas',
          'category': 'Politics'},
 'Q197': {'question': 'Government has the right: Monitor all e-mails and any other information '
                      'exchanged on the Internet',
          'category': 'Politics'},
 'Q198': {'question': 'Government has the right: Collect information about anyone living in '
                      '[COUNTRY] without their knowledge',
          'category': 'Politics'},
 'Q199': {'question': 'Interest in politics', 'category': 'Politics'},
 'Q200': {'question': 'How often discusses political matters with friends', 'category': 'Politics'},
 'Q201': {'question': 'Information source: Daily newspaper', 'category': 'Politics'},
 'Q202': {'question': 'Information source: TV news', 'category': 'Politics'},
 'Q203': {'question': 'Information source: Radio news', 'category': 'Politics'},
 'Q204': {'question': 'Information source: Mobile phone', 'category': 'Politics'},
 'Q205': {'question': 'Information source: Email', 'category': 'Politics'},
 'Q206': {'question': 'Information source: Internet', 'category': 'Politics'},
 'Q207': {'question': 'Information source: Social media (Facebook, Twitter, etc.)',
          'category': 'Politics'},
 'Q208': {'question': 'Information source: Talk with friends or colleagues',
          'category': 'Politics'},
 'Q209': {'question': 'Political action: Signing a petition', 'category': 'Politics'},
 'Q210': {'question': 'Political action: Joining in boycotts', 'category': 'Politics'},
 'Q211': {'question': 'Political action: Attending lawful/peaceful demonstrations',
          'category': 'Politics'},
 'Q212': {'question': 'Political action: Joining unofficial strikes', 'category': 'Politics'},
 'Q213': {'question': 'Social activism: Donating to a group or campaign', 'category': 'Politics'},
 'Q214': {'question': 'Social activism: Contacting a government official', 'category': 'Politics'},
 'Q216': {'question': 'Social activism: Encouraging others to vote', 'category': 'Politics'},
 'Q217': {'question': 'Political actions online: Searching information about politics and '
                      'political events',
          'category': 'Politics'},
 'Q218': {'question': 'Political actions online: Signing an electronic petition',
          'category': 'Politics'},
 'Q219': {'question': 'Political actions online: Encouraging other people to take any form of '
                      'political action',
          'category': 'Politics'},
 'Q220': {'question': 'Political actions online: Organizing political activities, events, protests',
          'category': 'Politics'},
 'Q221': {'question': 'Vote in elections: local level', 'category': 'Politics'},
 'Q222': {'question': 'Vote in elections: national level', 'category': 'Politics'},
 'Q223': {'question': 'Which party would you vote for if there were a national election tomorrow',
          'category': 'Politics'},
 'Q223_ABREV': {'question': 'Party preference Abbreviation', 'category': 'Politics'},
 'Q223_LOCAL': {'question': 'Party preference Local name', 'category': 'Politics'},
 'Q224': {'question': "How often in country's elections: Votes are counted fairly",
          'category': 'Politics'},
 'Q225': {'question': "How often in country's elections: Opposition candidates are prevented from "
                      'running',
          'category': 'Politics'},
 'Q226': {'question': "How often in country's elections: TV news favors the governing party",
          'category': 'Politics'},
 'Q227': {'question': "How often in country's elections: Voters are bribed",
          'category': 'Politics'},
 'Q228': {'question': "How often in country's elections: Journalists provide fair coverage of "
                      'elections',
          'category': 'Politics'},
 'Q229': {'question': "How often in country's elections: Election officials are fair",
          'category': 'Politics'},
 'Q230': {'question': "How often in country's elections: Rich people buy elections",
          'category': 'Politics'},
 'Q231': {'question': "How often in country's elections: Voters are threatened with violence at "
                      'the polls',
          'category': 'Politics'},
 'Q232': {'question': "How often in country's elections: Voters are offered a genuine choice in "
                      'the elections',
          'category': 'Politics'},
 'Q233': {'question': "How often in country's elections: Women have equal opportunities to run the "
                      'office',
          'category': 'Gender'},
 'Q234': {'question': 'Some people think that having honest elections makes a lot of difference in '
                      "their lives; other people think that it doesn't matter much",
          'category': 'Politics'},
 'Q235': {'question': 'Political system: Having a strong leader who does not have to bother with '
                      'parliament and elections',
          'category': 'Politics'},
 'Q236': {'question': 'Political system: Having experts, not government, make decisions according '
                      'to what they think is best for the country',
          'category': 'Politics'},
 'Q237': {'question': 'Political system: Having the army rule', 'category': 'Politics'},
 'Q238': {'question': 'Political system: Having a democratic political system',
          'category': 'Politics'},
 'Q239': {'question': 'Political system: Having a system governed by religious law in which there '
                      'are no political parties or elections',
          'category': 'Religion'},
 'Q240': {'question': 'Left-right political scale', 'category': 'Politics'},
 'Q241': {'question': 'Democracy: Governments tax the rich and subsidize the poor',
          'category': 'Economical'},
 'Q242': {'question': 'Democracy: Religious authorities interpret the laws',
          'category': 'Politics'},
 'Q243': {'question': 'Democracy: People choose their leaders in free elections',
          'category': 'Politics'},
 'Q244': {'question': 'Democracy: People receive state aid for unemployment',
          'category': 'Economical'},
 'Q245': {'question': 'Democracy: The army takes over when government is incompetent',
          'category': 'Politics'},
 'Q246': {'question': "Democracy: Civil rights protect people's liberty against oppression",
          'category': 'Morality'},
 'Q247': {'question': "Democracy: The state makes people's incomes equal",
          'category': 'Economical'},
 'Q248': {'question': 'Democracy: People obey their rulers', 'category': 'Morality'},
 'Q249': {'question': 'Democracy: Women have the same rights as men', 'category': 'Gender'},
 'Q250': {'question': 'Importance of democracy', 'category': 'Politics'},
 'Q251': {'question': 'How democratically is this country being governed today',
          'category': 'Politics'},
 'Q252': {'question': 'Satisfaction with the political system performance', 'category': 'Politics'},
 'Q253': {'question': 'Respect for individual human rights nowadays', 'category': 'Morality'},
 'Q254': {'question': 'National pride', 'category': 'Politics'},
 'Q255': {'question': 'Feel close to your village, town or city', 'category': 'Politics'},
 'Q256': {'question': 'Feel close to your district, region', 'category': 'Politics'},
 'Q257': {'question': 'Feel close to your country', 'category': 'Politics'},
 'Q258': {'question': 'Feel close to your continent', 'category': 'Politics'},
 'Q259': {'question': 'Feel close to the world', 'category': 'Politics'}}

COLS_TO_REMOVE = ['Q50',
 'Q51',
 'Q52',
 'Q53',
 'Q54',
 'Q55',
 'Q56',
 'Q82_EU',
 'Q91',
 'Q92',
 'Q93',
 'Q112',
 'Q118',
 'Q120',
 'Q131',
 'Q132',
 'Q133',
 'Q134',
 'Q135',
 'Q136',
 'Q137',
 'Q138',
 'Q139',
 'Q140',
 'Q141',
 'Q142',
 'Q143',
 'Q144',
 'Q145',
 'Q146',
 'Q147',
 'Q148',
 'Q199',
 'Q200',
 'Q201',
 'Q202',
 'Q203',
 'Q204',
 'Q205',
 'Q206',
 'Q207',
 'Q208',
 'Q209',
 'Q210',
 'Q211',
 'Q212',
 'Q213',
 'Q214',
 'Q215',
 'Q216',
 'Q217',
 'Q218',
 'Q219',
 'Q220',
 'Q221',
 'Q222',
 'Q223',
 'Q223_ABREV',
 'Q223_LOCAL',
 'Q224',
 'Q225',
 'Q226',
 'Q227',
 'Q228',
 'Q229',
 'Q230',
 'Q231',
 'Q232',
 'Q233',
 'Q223_LOCAL',
 'Q224',
 'Q234A',
 'Q225',
 'Q226',
 'Q227',
 'Q228',
 'Q229',
 'Q230',
 'Q231',
 'Q232',
 'Q233',
 'Q234',
 'Q234A',
 'Q251',
 'Q252',
 'Q253',
 'Q254',
 'Q255',
 'Q256',
 'Q257',
 'Q258',
 'Q259',
 'Q291UN3',
 'Q291UN5',
 'VOICE',
 'V2X_POLYARCHY',
 'V2X_LIBDEM',
 'V2X_PARTIPDEM',
 'V2X_DELIBDEM',
 'V2X_EGALDEM',
 'V2X_FREEXP_ALTINF',
 'V2X_FRASSOC_THICK',
 'V2XEL_FREFAIR',
 'V2XCL_ROL',
 'V2X_CSPART',
 'V2XEG_EQDR',
 'V2EXCRPTPS',
 'V2EXTHFTPS',
 'V2JUACCNT',
 'V2CLTRNSLW',
 'V2CLACJUST',
 'V2CLSOCGRP',
 'V2CLACFREE',
 'V2CLRELIG',
 'V2CSRLGREP',
 'V2MECENEFM',
 'V2MECENEFI',
 'V2MEBIAS',
 'V2PEPWRSES',
 'V2PEPWRGEN',
 'V2PEEDUEQ',
 'V2PEHEALTH',
 'V2PEAPSECON',
 'V2PEASJSOECON',
 'V2CLGENCL',
 'V2PEASJGEN',
 'V2PEASBGEN',
 'V2CAFRES',
 'V2CAFEXCH',
 'V2X_CORR',
 'V2X_GENDER',
 'V2X_GENCL',
 'V2X_GENPP',
 'V2X_RULE',
 'V2XCL_ACJST',
 'V2PSBARS',
 'V2PSORGS',
 'V2PSPRBRCH',
 'V2PSPRLNKS',
 'V2PSPLATS',
 'V2XNP_CLIENT',
 'V2XPS_PARTY']

ENGLISH_PROFICIENCY = {'NLD': {'country': 'Netherlands', 'score': 661, 'level': 'Very High Proficiency'},
 'SGP': {'country': 'Singapore', 'score': 642, 'level': 'Very High Proficiency'},
 'AUT': {'country': 'Austria', 'score': 628, 'level': 'Very High Proficiency'},
 'NOR': {'country': 'Norway', 'score': 627, 'level': 'Very High Proficiency'},
 'DNK': {'country': 'Denmark', 'score': 625, 'level': 'Very High Proficiency'},
 'BEL': {'country': 'Belgium', 'score': 620, 'level': 'Very High Proficiency'},
 'SWE': {'country': 'Sweden', 'score': 618, 'level': 'Very High Proficiency'},
 'FIN': {'country': 'Finland', 'score': 615, 'level': 'Very High Proficiency'},
 'PRT': {'country': 'Portugal', 'score': 614, 'level': 'Very High Proficiency'},
 'DEU': {'country': 'Germany', 'score': 613, 'level': 'Very High Proficiency'},
 'HRV': {'country': 'Croatia', 'score': 612, 'level': 'Very High Proficiency'},
 'ZAF': {'country': 'South Africa', 'score': 609, 'level': 'Very High Proficiency'},
 'POL': {'country': 'Poland', 'score': 600, 'level': 'Very High Proficiency'},
 'GRC': {'country': 'Greece', 'score': 598, 'level': 'High Proficiency'},
 'SVK': {'country': 'Slovakia', 'score': 597, 'level': 'High Proficiency'},
 'LUX': {'country': 'Luxembourg', 'score': 596, 'level': 'High Proficiency'},
 'ROU': {'country': 'Romania', 'score': 595, 'level': 'High Proficiency'},
 'HUN': {'country': 'Hungary', 'score': 590, 'level': 'High Proficiency'},
 'LTU': {'country': 'Lithuania', 'score': 589, 'level': 'High Proficiency'},
 'KEN': {'country': 'Kenya', 'score': 582, 'level': 'High Proficiency'},
 'BGR': {'country': 'Bulgaria', 'score': 581, 'level': 'High Proficiency'},
 'PHL': {'country': 'Philippines', 'score': 578, 'level': 'High Proficiency'},
 'CZE': {'country': 'Czech Republic', 'score': 575, 'level': 'High Proficiency'},
 'MYS': {'country': 'Malaysia', 'score': 574, 'level': 'High Proficiency'},
 'LVA': {'country': 'Latvia', 'score': 571, 'level': 'High Proficiency'},
 'EST': {'country': 'Estonia', 'score': 570, 'level': 'High Proficiency'},
 'SRB': {'country': 'Serbia', 'score': 567, 'level': 'High Proficiency'},
 'NGA': {'country': 'Nigeria', 'score': 564, 'level': 'High Proficiency'},
 'CHE': {'country': 'Switzerland', 'score': 563, 'level': 'High Proficiency'},
 'ARG': {'country': 'Argentina', 'score': 562, 'level': 'High Proficiency'},
 'HKG': {'country': 'Hong Kong', 'score': 561, 'level': 'High Proficiency'},
 'ITA': {'country': 'Italy', 'score': 548, 'level': 'Moderate Proficiency'},
 'ESP': {'country': 'Spain', 'score': 545, 'level': 'Moderate Proficiency'},
 'FRA': {'country': 'France', 'score': 541, 'level': 'Moderate Proficiency'},
 'UKR': {'country': 'Ukraine', 'score': 539, 'level': 'Moderate Proficiency'},
 'KOR': {'country': 'South Korea', 'score': 537, 'level': 'Moderate Proficiency'},
 'CRI': {'country': 'Costa Rica', 'score': 536, 'level': 'Moderate Proficiency'},
 'CUB': {'country': 'Cuba', 'score': 535, 'level': 'Moderate Proficiency'},
 'BLR': {'country': 'Belarus', 'score': 533, 'level': 'Moderate Proficiency'},
 'RUS': {'country': 'Russia', 'score': 530, 'level': 'Moderate Proficiency'},
 'GHA': {'country': 'Ghana', 'score': 529, 'level': 'Moderate Proficiency'},
 'MDA': {'country': 'Moldova', 'score': 528, 'level': 'Moderate Proficiency'},
 'PRY': {'country': 'Paraguay', 'score': 526, 'level': 'Moderate Proficiency'},
 'BOL': {'country': 'Bolivia', 'score': 525, 'level': 'Moderate Proficiency'},
 'CHL': {'country': 'Chile', 'score': 524, 'level': 'Moderate Proficiency'},
 'GEO': {'country': 'Georgia', 'score': 524, 'level': 'Moderate Proficiency'},
 'ALB': {'country': 'Albania', 'score': 523, 'level': 'Moderate Proficiency'},
 'HND': {'country': 'Honduras', 'score': 522, 'level': 'Moderate Proficiency'},
 'URY': {'country': 'Uruguay', 'score': 521, 'level': 'Moderate Proficiency'},
 'SLV': {'country': 'El Salvador', 'score': 519, 'level': 'Moderate Proficiency'},
 'PER': {'country': 'Peru', 'score': 517, 'level': 'Moderate Proficiency'},
 'IND': {'country': 'India', 'score': 516, 'level': 'Moderate Proficiency'},
 'DOM': {'country': 'Dominican Republic', 'score': 514, 'level': 'Moderate Proficiency'},
 'LBN': {'country': 'Lebanon', 'score': 513, 'level': 'Moderate Proficiency'},
 'UGA': {'country': 'Uganda', 'score': 512, 'level': 'Moderate Proficiency'},
 'TUN': {'country': 'Tunisia', 'score': 511, 'level': 'Moderate Proficiency'},
 'ARM': {'country': 'Armenia', 'score': 506, 'level': 'Moderate Proficiency'},
 'BRA': {'country': 'Brazil', 'score': 505, 'level': 'Moderate Proficiency'},
 'GTM': {'country': 'Guatemala', 'score': 505, 'level': 'Moderate Proficiency'},
 'VNM': {'country': 'Vietnam', 'score': 502, 'level': 'Moderate Proficiency'},
 'NIC': {'country': 'Nicaragua', 'score': 499, 'level': 'Low Proficiency'},
 'CHN': {'country': 'China', 'score': 498, 'level': 'Low Proficiency'},
 'TZA': {'country': 'Tanzania', 'score': 496, 'level': 'Low Proficiency'},
 'TUR': {'country': 'Turkey', 'score': 495, 'level': 'Low Proficiency'},
 'NPL': {'country': 'Nepal', 'score': 494, 'level': 'Low Proficiency'},
 'BGD': {'country': 'Bangladesh', 'score': 493, 'level': 'Low Proficiency'},
 'VEN': {'country': 'Venezuela', 'score': 492, 'level': 'Low Proficiency'},
 'ETH': {'country': 'Ethiopia', 'score': 490, 'level': 'Low Proficiency'},
 'IRN': {'country': 'Iran', 'score': 489, 'level': 'Low Proficiency'},
 'PAK': {'country': 'Pakistan', 'score': 488, 'level': 'Low Proficiency'},
 'LKA': {'country': 'Sri Lanka', 'score': 487, 'level': 'Low Proficiency'},
 'MNG': {'country': 'Mongolia', 'score': 485, 'level': 'Low Proficiency'},
 'QAT': {'country': 'Qatar', 'score': 484, 'level': 'Low Proficiency'},
 'ISR': {'country': 'Israel', 'score': 483, 'level': 'Low Proficiency'},
 'PAN': {'country': 'Panama', 'score': 482, 'level': 'Low Proficiency'},
 'MAR': {'country': 'Morocco', 'score': 478, 'level': 'Low Proficiency'},
 'COL': {'country': 'Colombia', 'score': 477, 'level': 'Low Proficiency'},
 'DZA': {'country': 'Algeria', 'score': 476, 'level': 'Low Proficiency'},
 'ARE': {'country': 'United Arab Emirates', 'score': 476, 'level': 'Low Proficiency'},
 'JPN': {'country': 'Japan', 'score': 475, 'level': 'Low Proficiency'},
 'IDN': {'country': 'Indonesia', 'score': 469, 'level': 'Low Proficiency'},
 'ECU': {'country': 'Ecuador', 'score': 466, 'level': 'Low Proficiency'},
 'SYR': {'country': 'Syria', 'score': 461, 'level': 'Low Proficiency'},
 'KWT': {'country': 'Kuwait', 'score': 459, 'level': 'Low Proficiency'},
 'EGY': {'country': 'Egypt', 'score': 454, 'level': 'Low Proficiency'},
 'MOZ': {'country': 'Mozambique', 'score': 453, 'level': 'Low Proficiency'},
 'AFG': {'country': 'Afghanistan', 'score': 450, 'level': 'Low Proficiency'},
 'MEX': {'country': 'Mexico', 'score': 447, 'level': 'Very Low Proficiency'},
 'UZB': {'country': 'Uzbekistan', 'score': 446, 'level': 'Very Low Proficiency'},
 'JOR': {'country': 'Jordan', 'score': 443, 'level': 'Very Low Proficiency'},
 'KGZ': {'country': 'Kyrgyzstan', 'score': 442, 'level': 'Very Low Proficiency'},
 'AZE': {'country': 'Azerbaijan', 'score': 440, 'level': 'Very Low Proficiency'},
 'MMR': {'country': 'Myanmar', 'score': 437, 'level': 'Very Low Proficiency'},
 'KHM': {'country': 'Cambodia', 'score': 434, 'level': 'Very Low Proficiency'},
 'SDN': {'country': 'Sudan', 'score': 426, 'level': 'Very Low Proficiency'},
 'CMR': {'country': 'Cameroon', 'score': 425, 'level': 'Very Low Proficiency'},
 'THA': {'country': 'Thailand', 'score': 423, 'level': 'Very Low Proficiency'},
 'HTI': {'country': 'Haiti', 'score': 421, 'level': 'Very Low Proficiency'},
 'KAZ': {'country': 'Kazakhstan', 'score': 420, 'level': 'Very Low Proficiency'},
 'SOM': {'country': 'Somalia', 'score': 414, 'level': 'Very Low Proficiency'},
 'OMN': {'country': 'Oman', 'score': 412, 'level': 'Very Low Proficiency'},
 'SAU': {'country': 'Saudi Arabia', 'score': 406, 'level': 'Very Low Proficiency'},
 'IRQ': {'country': 'Iraq', 'score': 404, 'level': 'Very Low Proficiency'},
 'CIV': {'country': 'Ivory Coast', 'score': 403, 'level': 'Very Low Proficiency'},
 'AGO': {'country': 'Angola', 'score': 402, 'level': 'Very Low Proficiency'},
 'TJK': {'country': 'Tajikistan', 'score': 397, 'level': 'Very Low Proficiency'},
 'RWA': {'country': 'Rwanda', 'score': 392, 'level': 'Very Low Proficiency'},
 'LBY': {'country': 'Libya', 'score': 390, 'level': 'Very Low Proficiency'},
 'YEM': {'country': 'Yemen', 'score': 370, 'level': 'Very Low Proficiency'},
 'COD': {'country': 'Democratic Republic of the Congo',
         'score': 367,
         'level': 'Very Low Proficiency'},
 'LAO': {'country': 'Laos', 'score': 364, 'level': 'Very Low Proficiency'}}

